services:


  flask:
    image: flask-ec2-app1
    restart: always
    build:
      context: flask
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - APP_VERSION=0.1.0

    
